<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\User;
use App\Enums\UserRole;
use Illuminate\Support\Facades\Hash;

class datasiswa extends Seeder
{
    /**
     * Jalankan seeder untuk 10 data siswa.
     */
    public function run(): void
    {
        $siswaData = [
            [
                'name' => 'Ahmad Fauzi',
                'email' => 'ahmad.fauzi@example.com',
                'password' => Hash::make('siswa123'),
                'nisn' => '1000000001',
                'nis' => 20001,
                'kelas' => 'X IPA 1',
                'jenis_kelamin' => 'laki_laki',
                'tempat_lahir' => 'Jakarta',
                'tanggal_lahir' => '2006-01-10',
                'agama' => 'islam',
                'alamat' => 'Jl. Melati No. 1, Jakarta',
                'no_telp' => 628111111111,
                'pas_foto' => null,
                'role' => UserRole::SISWA,
            ],
            [
                'name' => 'Budi Santoso',
                'email' => 'budi.santoso@example.com',
                'password' => Hash::make('siswa123'),
                'nisn' => '1000000002',
                'nis' => 20002,
                'kelas' => 'X IPA 2',
                'jenis_kelamin' => 'laki_laki',
                'tempat_lahir' => 'Bandung',
                'tanggal_lahir' => '2006-02-15',
                'agama' => 'kristen',
                'alamat' => 'Jl. Mawar No. 2, Bandung',
                'no_telp' => 628122222222,
                'pas_foto' => null,
                'role' => UserRole::SISWA,
            ],
            [
                'name' => 'Citra Dewi',
                'email' => 'citra.dewi@example.com',
                'password' => Hash::make('siswa123'),
                'nisn' => '1000000003',
                'nis' => 20003,
                'kelas' => 'X IPA 3',
                'jenis_kelamin' => 'perempuan',
                'tempat_lahir' => 'Surabaya',
                'tanggal_lahir' => '2006-03-20',
                'agama' => 'katholik',
                'alamat' => 'Jl. Kenanga No. 3, Surabaya',
                'no_telp' => 628133333333,
                'pas_foto' => null,
                'role' => UserRole::SISWA,
            ],
            [
                'name' => 'Dewi Lestari',
                'email' => 'dewi.lestari@example.com',
                'password' => Hash::make('siswa123'),
                'nisn' => '1000000004',
                'nis' => 20004,
                'kelas' => 'X IPA 4',
                'jenis_kelamin' => 'perempuan',
                'tempat_lahir' => 'Medan',
                'tanggal_lahir' => '2006-04-25',
                'agama' => 'hindu',
                'alamat' => 'Jl. Anggrek No. 4, Medan',
                'no_telp' => 628144444444,
                'pas_foto' => null,
                'role' => UserRole::SISWA,
            ],
            [
                'name' => 'Eka Pratama',
                'email' => 'eka.pratama@example.com',
                'password' => Hash::make('siswa123'),
                'nisn' => '1000000005',
                'nis' => 20005,
                'kelas' => 'X IPA 5',
                'jenis_kelamin' => 'laki_laki',
                'tempat_lahir' => 'Semarang',
                'tanggal_lahir' => '2006-05-30',
                'agama' => 'buddha',
                'alamat' => 'Jl. Dahlia No. 5, Semarang',
                'no_telp' => 628155555555,
                'pas_foto' => null,
                'role' => UserRole::SISWA,
            ],
            [
                'name' => 'Fajar Nugroho',
                'email' => 'fajar.nugroho@example.com',
                'password' => Hash::make('siswa123'),
                'nisn' => '1000000006',
                'nis' => 20006,
                'kelas' => 'X IPA 6',
                'jenis_kelamin' => 'laki_laki',
                'tempat_lahir' => 'Yogyakarta',
                'tanggal_lahir' => '2006-06-05',
                'agama' => 'konghucu',
                'alamat' => 'Jl. Flamboyan No. 6, Yogyakarta',
                'no_telp' => 628166666666,
                'pas_foto' => null,
                'role' => UserRole::SISWA,
            ],
            [
                'name' => 'Gita Sari',
                'email' => 'gita.sari@example.com',
                'password' => Hash::make('siswa123'),
                'nisn' => '1000000007',
                'nis' => 20007,
                'kelas' => 'X IPA 7',
                'jenis_kelamin' => 'perempuan',
                'tempat_lahir' => 'Makassar',
                'tanggal_lahir' => '2006-07-10',
                'agama' => 'islam',
                'alamat' => 'Jl. Cempaka No. 7, Makassar',
                'no_telp' => 628177777777,
                'pas_foto' => null,
                'role' => UserRole::SISWA,
            ],
            [
                'name' => 'Hadi Wijaya',
                'email' => 'hadi.wijaya@example.com',
                'password' => Hash::make('siswa123'),
                'nisn' => '1000000008',
                'nis' => 20008,
                'kelas' => 'X IPA 8',
                'jenis_kelamin' => 'laki_laki',
                'tempat_lahir' => 'Palembang',
                'tanggal_lahir' => '2006-08-15',
                'agama' => 'kristen',
                'alamat' => 'Jl. Teratai No. 8, Palembang',
                'no_telp' => 628188888888,
                'pas_foto' => null,
                'role' => UserRole::SISWA,
            ],
            [
                'name' => 'Indah Permata',
                'email' => 'indah.permata@example.com',
                'password' => Hash::make('siswa123'),
                'nisn' => '1000000009',
                'nis' => 20009,
                'kelas' => 'X IPA 9',
                'jenis_kelamin' => 'perempuan',
                'tempat_lahir' => 'Balikpapan',
                'tanggal_lahir' => '2006-09-20',
                'agama' => 'katholik',
                'alamat' => 'Jl. Sawo No. 9, Balikpapan',
                'no_telp' => 628199999999,
                'pas_foto' => null,
                'role' => UserRole::SISWA,
            ],
            [
                'name' => 'Joko Susilo',
                'email' => 'joko.susilo@example.com',
                'password' => Hash::make('siswa123'),
                'nisn' => '1000000010',
                'nis' => 20010,
                'kelas' => 'X IPA 10',
                'jenis_kelamin' => 'laki_laki',
                'tempat_lahir' => 'Denpasar',
                'tanggal_lahir' => '2006-10-25',
                'agama' => 'hindu',
                'alamat' => 'Jl. Mangga No. 10, Denpasar',
                'no_telp' => 628101010101,
                'pas_foto' => null,
                'role' => UserRole::SISWA,
            ],
        ];

        foreach ($siswaData as $data) {
            User::updateOrCreate([
                'nisn' => $data['nisn'],
            ], $data);
        }
    }
} 