<?php

namespace Database\Seeders;

use App\Models\Classroom;
use App\Models\Student;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class StudentSeeder extends Seeder
{
    public function run(): void
    {
        $classXMipa1 = Classroom::where('name', 'X-MIPA 1')->first();
        $classXMipa2 = Classroom::where('name', 'X-MIPA 2')->first();
        $classXiMipa1 = Classroom::where('name', 'XI-MIPA 1')->first();
        $classXiiMipa1 = Classroom::where('name', 'XII-MIPA 1')->first();

        $students = [
            // ── Kelas X-MIPA 1 (6 siswa aktif) ──────────────────────────────
            [
                'name' => 'Ahmad Rizki Pratama',
                'email' => 'ahmad.rizki@siswa.sch.id',
                'nis' => '2026001',
                'nisn' => '0061234501',
                'classroom_id' => $classXMipa1?->id,
                'grade' => $classXMipa1?->name ?? 'X-MIPA 1',
                'academic_status' => 'active',
                'gender' => 'male',
                'place_of_birth' => 'Jakarta',
                'date_of_birth' => '2009-03-12',
                'religion' => 'Islam',
                'phone' => '081211110001',
                'address' => 'Jl. Kebon Jeruk No.12, Jakarta Barat',
            ],
            [
                'name' => 'Siti Nurhaliza',
                'email' => 'siti.nur@siswa.sch.id',
                'nis' => '2026002',
                'nisn' => '0061234502',
                'classroom_id' => $classXMipa1?->id,
                'grade' => $classXMipa1?->name ?? 'X-MIPA 1',
                'academic_status' => 'active',
                'gender' => 'female',
                'place_of_birth' => 'Bandung',
                'date_of_birth' => '2009-07-20',
                'religion' => 'Islam',
                'phone' => '081211110002',
                'address' => 'Jl. Dago No.55, Bandung',
            ],
            [
                'name' => 'Budi Santoso',
                'email' => 'budi.santoso@siswa.sch.id',
                'nis' => '2026003',
                'nisn' => '0061234503',
                'classroom_id' => $classXMipa1?->id,
                'grade' => $classXMipa1?->name ?? 'X-MIPA 1',
                'academic_status' => 'active',
                'gender' => 'male',
                'place_of_birth' => 'Surabaya',
                'date_of_birth' => '2009-01-05',
                'religion' => 'Islam',
                'phone' => '081211110003',
                'address' => 'Jl. Rungkut No.8, Surabaya',
            ],
            [
                'name' => 'Dewi Anggraeni',
                'email' => 'dewi.ang@siswa.sch.id',
                'nis' => '2026004',
                'nisn' => '0061234504',
                'classroom_id' => $classXMipa1?->id,
                'grade' => $classXMipa1?->name ?? 'X-MIPA 1',
                'academic_status' => 'active',
                'gender' => 'female',
                'place_of_birth' => 'Semarang',
                'date_of_birth' => '2009-09-17',
                'religion' => 'Islam',
                'phone' => '081211110004',
                'address' => 'Jl. Pemuda No.22, Semarang',
            ],
            [
                'name' => 'Rizal Maulana',
                'email' => 'rizal.maulana@siswa.sch.id',
                'nis' => '2026005',
                'nisn' => '0061234505',
                'classroom_id' => $classXMipa1?->id,
                'grade' => $classXMipa1?->name ?? 'X-MIPA 1',
                'academic_status' => 'active',
                'gender' => 'male',
                'place_of_birth' => 'Yogyakarta',
                'date_of_birth' => '2009-05-30',
                'religion' => 'Islam',
                'phone' => '081211110005',
                'address' => 'Jl. Malioboro No.1, Yogyakarta',
            ],
            [
                'name' => 'Nabila Putri Azzahra',
                'email' => 'nabila.putri@siswa.sch.id',
                'nis' => '2026006',
                'nisn' => '0061234506',
                'classroom_id' => $classXMipa1?->id,
                'grade' => $classXMipa1?->name ?? 'X-MIPA 1',
                'academic_status' => 'active',
                'gender' => 'female',
                'place_of_birth' => 'Bogor',
                'date_of_birth' => '2009-08-14',
                'religion' => 'Islam',
                'phone' => '081211110006',
                'address' => 'Jl. Pajajaran No.99, Bogor',
            ],

            // ── Kelas X-MIPA 2 (4 siswa aktif) ──────────────────────────────
            [
                'name' => 'Farhan Ramadhan',
                'email' => 'farhan.ramadhan@siswa.sch.id',
                'nis' => '2026011',
                'nisn' => '0061234511',
                'classroom_id' => $classXMipa2?->id,
                'grade' => $classXMipa2?->name ?? 'X-MIPA 2',
                'academic_status' => 'active',
                'gender' => 'male',
                'place_of_birth' => 'Medan',
                'date_of_birth' => '2009-04-11',
                'religion' => 'Islam',
                'phone' => '081211110011',
                'address' => 'Jl. Gatot Subroto No.10, Medan',
            ],
            [
                'name' => 'Aulia Zahra',
                'email' => 'aulia.zahra@siswa.sch.id',
                'nis' => '2026012',
                'nisn' => '0061234512',
                'classroom_id' => $classXMipa2?->id,
                'grade' => $classXMipa2?->name ?? 'X-MIPA 2',
                'academic_status' => 'active',
                'gender' => 'female',
                'place_of_birth' => 'Padang',
                'date_of_birth' => '2009-10-05',
                'religion' => 'Islam',
                'phone' => '081211110012',
                'address' => 'Jl. Khatib Sulaiman No.4, Padang',
            ],
            [
                'name' => 'Kevin Sanjaya',
                'email' => 'kevin.sanjaya@siswa.sch.id',
                'nis' => '2026013',
                'nisn' => '0061234513',
                'classroom_id' => $classXMipa2?->id,
                'grade' => $classXMipa2?->name ?? 'X-MIPA 2',
                'academic_status' => 'active',
                'gender' => 'male',
                'place_of_birth' => 'Denpasar',
                'date_of_birth' => '2009-02-18',
                'religion' => 'Hindu',
                'phone' => '081211110013',
                'address' => 'Jl. Teuku Umar No.55, Denpasar',
            ],
            [
                'name' => 'Clarissa Stephanie',
                'email' => 'clarissa.stephanie@siswa.sch.id',
                'nis' => '2026014',
                'nisn' => '0061234514',
                'classroom_id' => $classXMipa2?->id,
                'grade' => $classXMipa2?->name ?? 'X-MIPA 2',
                'academic_status' => 'active',
                'gender' => 'female',
                'place_of_birth' => 'Surabaya',
                'date_of_birth' => '2009-12-01',
                'religion' => 'Kristen',
                'phone' => '081211110014',
                'address' => 'Jl. Mayjen Sungkono No.80, Surabaya',
            ],

            // ── Kelas XI-MIPA 1 (6 siswa aktif) ─────────────────────────────
            [
                'name' => 'Dimas Arya Pamungkas',
                'email' => 'dimas.arya@siswa.sch.id',
                'nis' => '2025001',
                'nisn' => '0051234501',
                'classroom_id' => $classXiMipa1?->id,
                'grade' => $classXiMipa1?->name ?? 'XI-MIPA 1',
                'academic_status' => 'active',
                'gender' => 'male',
                'place_of_birth' => 'Solo',
                'date_of_birth' => '2008-01-15',
                'religion' => 'Islam',
                'phone' => '081211110021',
                'address' => 'Jl. Slamet Riyadi No.15, Solo',
            ],
            [
                'name' => 'Jessica Tanuwijaya',
                'email' => 'jessica.tan@siswa.sch.id',
                'nis' => '2025002',
                'nisn' => '0051234502',
                'classroom_id' => $classXiMipa1?->id,
                'grade' => $classXiMipa1?->name ?? 'XI-MIPA 1',
                'academic_status' => 'active',
                'gender' => 'female',
                'place_of_birth' => 'Jakarta',
                'date_of_birth' => '2008-06-25',
                'religion' => 'Buddha',
                'phone' => '081211110022',
                'address' => 'Jl. Pluit Raya No.7, Jakarta Utara',
            ],
            [
                'name' => 'Reza Fahlevi',
                'email' => 'reza.fahlevi@siswa.sch.id',
                'nis' => '2025003',
                'nisn' => '0051234503',
                'classroom_id' => $classXiMipa1?->id,
                'grade' => $classXiMipa1?->name ?? 'XI-MIPA 1',
                'academic_status' => 'active',
                'gender' => 'male',
                'place_of_birth' => 'Malang',
                'date_of_birth' => '2008-09-08',
                'religion' => 'Islam',
                'phone' => '081211110023',
                'address' => 'Jl. Buring No.3, Malang',
            ],
            [
                'name' => 'Tiara Andini',
                'email' => 'tiara.andini@siswa.sch.id',
                'nis' => '2025004',
                'nisn' => '0051234504',
                'classroom_id' => $classXiMipa1?->id,
                'grade' => $classXiMipa1?->name ?? 'XI-MIPA 1',
                'academic_status' => 'active',
                'gender' => 'female',
                'place_of_birth' => 'Jember',
                'date_of_birth' => '2008-11-20',
                'religion' => 'Islam',
                'phone' => '081211110024',
                'address' => 'Jl. Kalimantan No.12, Jember',
            ],
            [
                'name' => 'Alif Ramadhan Syahputra',
                'email' => 'alif.ramadhan@siswa.sch.id',
                'nis' => '2025005',
                'nisn' => '0051234505',
                'classroom_id' => $classXiMipa1?->id,
                'grade' => $classXiMipa1?->name ?? 'XI-MIPA 1',
                'academic_status' => 'active',
                'gender' => 'male',
                'place_of_birth' => 'Palembang',
                'date_of_birth' => '2008-04-03',
                'religion' => 'Islam',
                'phone' => '081211110025',
                'address' => 'Jl. Kolonel Atmo No.27, Palembang',
            ],
            [
                'name' => 'Syifa Hadju Maharani',
                'email' => 'syifa.hadju@siswa.sch.id',
                'nis' => '2025006',
                'nisn' => '0051234506',
                'classroom_id' => $classXiMipa1?->id,
                'grade' => $classXiMipa1?->name ?? 'XI-MIPA 1',
                'academic_status' => 'active',
                'gender' => 'female',
                'place_of_birth' => 'Jakarta',
                'date_of_birth' => '2008-07-13',
                'religion' => 'Islam',
                'phone' => '081211110026',
                'address' => 'Jl. Tebet Barat No.14, Jakarta Selatan',
            ],

            // ── Kelas XII-MIPA 1 (4 siswa aktif tingkat akhir) ──────────────
            [
                'name' => 'Fajar Alfian Pratama',
                'email' => 'fajar.alfian@siswa.sch.id',
                'nis' => '2024001',
                'nisn' => '0041234501',
                'classroom_id' => $classXiiMipa1?->id,
                'grade' => $classXiiMipa1?->name ?? 'XII-MIPA 1',
                'academic_status' => 'active',
                'gender' => 'male',
                'place_of_birth' => 'Bandung',
                'date_of_birth' => '2007-03-07',
                'religion' => 'Islam',
                'phone' => '081211110031',
                'address' => 'Jl. Pasirkaliki No.20, Bandung',
            ],
            [
                'name' => 'Annisa Tri Hapsari',
                'email' => 'annisa.tri@siswa.sch.id',
                'nis' => '2024002',
                'nisn' => '0041234502',
                'classroom_id' => $classXiiMipa1?->id,
                'grade' => $classXiiMipa1?->name ?? 'XII-MIPA 1',
                'academic_status' => 'active',
                'gender' => 'female',
                'place_of_birth' => 'Semarang',
                'date_of_birth' => '2007-05-19',
                'religion' => 'Islam',
                'phone' => '081211110032',
                'address' => 'Jl. Pandanaran No.10, Semarang',
            ],
            [
                'name' => 'Galih Rakasiwi',
                'email' => 'galih.rakasiwi@siswa.sch.id',
                'nis' => '2024003',
                'nisn' => '0041234503',
                'classroom_id' => $classXiiMipa1?->id,
                'grade' => $classXiiMipa1?->name ?? 'XII-MIPA 1',
                'academic_status' => 'active',
                'gender' => 'male',
                'place_of_birth' => 'Yogyakarta',
                'date_of_birth' => '2007-08-22',
                'religion' => 'Islam',
                'phone' => '081211110033',
                'address' => 'Jl. Kaliurang KM 5, Yogyakarta',
            ],
            [
                'name' => 'Ratna Galih Kirana',
                'email' => 'ratna.galih@siswa.sch.id',
                'nis' => '2024004',
                'nisn' => '0041234504',
                'classroom_id' => $classXiiMipa1?->id,
                'grade' => $classXiiMipa1?->name ?? 'XII-MIPA 1',
                'academic_status' => 'active',
                'gender' => 'female',
                'place_of_birth' => 'Surakarta',
                'date_of_birth' => '2007-10-30',
                'religion' => 'Islam',
                'phone' => '081211110034',
                'address' => 'Jl. Veteran No.5, Surakarta',
            ],

            // ── Alumni / Lulusan (4 siswa alumni) ────────────────────────────
            [
                'name' => 'Bagus Wicaksono (Alumni)',
                'email' => 'bagus.wicaksono@alumni.sch.id',
                'nis' => '2023001',
                'nisn' => '0031234501',
                'classroom_id' => null,
                'grade' => 'XII-MIPA 1',
                'academic_status' => 'graduated',
                'gender' => 'male',
                'place_of_birth' => 'Jakarta',
                'date_of_birth' => '2006-02-10',
                'religion' => 'Islam',
                'phone' => '081211110041',
                'address' => 'Jl. Kemang Raya No.12, Jakarta Selatan',
            ],
            [
                'name' => 'Melati Kusuma Wardani (Alumni)',
                'email' => 'melati.kusuma@alumni.sch.id',
                'nis' => '2023002',
                'nisn' => '0031234502',
                'classroom_id' => null,
                'grade' => 'XII-MIPA 1',
                'academic_status' => 'graduated',
                'gender' => 'female',
                'place_of_birth' => 'Bandung',
                'date_of_birth' => '2006-06-18',
                'religion' => 'Islam',
                'phone' => '081211110042',
                'address' => 'Jl. Setiabudi No.45, Bandung',
            ],
            [
                'name' => 'Rian Hidayat (Alumni)',
                'email' => 'rian.hidayat@alumni.sch.id',
                'nis' => '2023003',
                'nisn' => '0031234503',
                'classroom_id' => null,
                'grade' => 'XII-IPS 1',
                'academic_status' => 'graduated',
                'gender' => 'male',
                'place_of_birth' => 'Surabaya',
                'date_of_birth' => '2006-09-04',
                'religion' => 'Islam',
                'phone' => '081211110043',
                'address' => 'Jl. Darmo No.99, Surabaya',
            ],
            [
                'name' => 'Putri Ayu Wandira (Alumni)',
                'email' => 'putri.ayu@alumni.sch.id',
                'nis' => '2023004',
                'nisn' => '0031234504',
                'classroom_id' => null,
                'grade' => 'XII-IPS 1',
                'academic_status' => 'graduated',
                'gender' => 'female',
                'place_of_birth' => 'Malang',
                'date_of_birth' => '2006-12-25',
                'religion' => 'Islam',
                'phone' => '081211110044',
                'address' => 'Jl. Soekarno Hatta No.10, Malang',
            ],
        ];

        foreach ($students as $data) {
            $user = User::updateOrCreate(
                ['email' => $data['email']],
                [
                    'name' => $data['name'],
                    'password' => Hash::make('password123'),
                ]
            );

            if (! $user->hasRole('siswa')) {
                $user->assignRole('siswa');
            }

            Student::updateOrCreate(
                ['user_id' => $user->id],
                [
                    'classroom_id' => $data['classroom_id'],
                    'nis' => $data['nis'],
                    'nisn' => $data['nisn'],
                    'grade' => $data['grade'],
                    'academic_status' => $data['academic_status'],
                    'gender' => $data['gender'],
                    'place_of_birth' => $data['place_of_birth'],
                    'date_of_birth' => $data['date_of_birth'],
                    'religion' => $data['religion'],
                    'phone_number' => $data['phone'],
                    'address' => $data['address'],
                ]
            );
        }

        $this->command->info('✅ 24 siswa (20 siswa aktif tersebar di rombel + 4 alumni) berhasil di-seed.');
    }
}
